---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-admission
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-admission-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: gpu-admission
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-admission-config
  namespace: kube-system
data:
  config.yaml: |-
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
      resourceName: gpu-admission
      resourceNamespace: kube-system
    profiles:
      - schedulerName: gpu-admission
        plugins:
          filter:
            enabled:
            - name: gpu-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-admission
  namespace: kube-system
spec:
  # replica > 1 require leaderElect=true
  replicas: 1 
  selector:
    matchLabels:
      app: gpu-admission
  template:
    metadata:
      labels:
        app: gpu-admission
    spec:
      serviceAccountName: gpu-admission
      containers:
        - name: gpu-admission
          image: localhost:5000/test/gpu-admission:1.23.17
          imagePullPolicy: Always
          args:
            - /gpu-admission
            - --config=/config/config.yaml
            - --v=3
          volumeMounts:
            - name: gpu-admission-config
              mountPath: /config
      volumes:
        - name: gpu-admission-config
          configMap:
            name: gpu-admission-config